export interface LanguageData {
  id: string;
  name: string;
  nativeName: string;
  audioUrl: string;
  correctLat: number;
  correctLng: number;
  country: string;
  funFact: string;
  difficulty: "easy" | "medium" | "hard";
}

export const languages: LanguageData[] = [
  {
    id: "english",
    name: "English",
    nativeName: "English",
    audioUrl: "/audio/english.mp3",
    correctLat: 51.5,
    correctLng: -0.12,
    country: "United Kingdom",
    funFact: "English has more words than any other language — over 170,000 in current use, with about 47,000 obsolete words.",
    difficulty: "easy",
  },
  {
    id: "spanish",
    name: "Spanish",
    nativeName: "Espanol",
    audioUrl: "/audio/spanish.mp3",
    correctLat: 40.42,
    correctLng: -3.7,
    country: "Spain",
    funFact: "Spanish is the official language of 20 countries and has over 500 million native speakers worldwide.",
    difficulty: "easy",
  },
  {
    id: "french",
    name: "French",
    nativeName: "Francais",
    audioUrl: "/audio/french.mp3",
    correctLat: 48.86,
    correctLng: 2.35,
    country: "France",
    funFact: "French was the official language of England for over 300 years after the Norman Conquest of 1066.",
    difficulty: "easy",
  },
  {
    id: "german",
    name: "German",
    nativeName: "Deutsch",
    audioUrl: "/audio/german.mp3",
    correctLat: 52.52,
    correctLng: 13.41,
    country: "Germany",
    funFact: "German has unique compound words — 'Handschuh' (glove) literally means 'hand shoe'.",
    difficulty: "easy",
  },
  {
    id: "italian",
    name: "Italian",
    nativeName: "Italiano",
    audioUrl: "/audio/italian.mp3",
    correctLat: 41.9,
    correctLng: 12.5,
    country: "Italy",
    funFact: "Italian became a unified language only in 1861 when Italy was unified — before that, everyone spoke regional dialects.",
    difficulty: "easy",
  },
  {
    id: "portuguese",
    name: "Portuguese",
    nativeName: "Portugues",
    audioUrl: "/audio/portuguese.mp3",
    correctLat: -22.91,
    correctLng: -43.17,
    country: "Brazil",
    funFact: "Portuguese is spoken on every continent and is the most spoken language in the Southern Hemisphere.",
    difficulty: "medium",
  },
  {
    id: "russian",
    name: "Russian",
    nativeName: "Russkiy",
    audioUrl: "/audio/russian.mp3",
    correctLat: 55.76,
    correctLng: 37.62,
    country: "Russia",
    funFact: "Russian was the first language spoken in outer space by cosmonaut Yuri Gagarin in 1961.",
    difficulty: "medium",
  },
  {
    id: "japanese",
    name: "Japanese",
    nativeName: "Nihongo",
    audioUrl: "/audio/japanese.mp3",
    correctLat: 35.68,
    correctLng: 139.69,
    country: "Japan",
    funFact: "Japanese has three writing systems: Hiragana, Katakana, and Kanji — and uses all three in everyday text.",
    difficulty: "medium",
  },
  {
    id: "korean",
    name: "Korean",
    nativeName: "Hangugeo",
    audioUrl: "/audio/korean.mp3",
    correctLat: 37.57,
    correctLng: 126.98,
    country: "South Korea",
    funFact: "The Korean alphabet Hangul was invented by King Sejong the Great in 1443 and is considered one of the most scientific writing systems.",
    difficulty: "medium",
  },
  {
    id: "mandarin",
    name: "Mandarin Chinese",
    nativeName: "Putonghua",
    audioUrl: "/audio/mandarin.mp3",
    correctLat: 39.9,
    correctLng: 116.4,
    country: "China",
    funFact: "Mandarin is a tonal language with 4 tones — the same syllable can have completely different meanings depending on the tone.",
    difficulty: "medium",
  },
  {
    id: "hindi",
    name: "Hindi",
    nativeName: "Hindi",
    audioUrl: "/audio/hindi.mp3",
    correctLat: 28.61,
    correctLng: 77.21,
    country: "India",
    funFact: "Hindi and Urdu are mutually intelligible when spoken — they diverge mainly in their writing systems and formal vocabulary.",
    difficulty: "medium",
  },
  {
    id: "arabic",
    name: "Arabic",
    nativeName: "Al-Arabiyya",
    audioUrl: "/audio/arabic.mp3",
    correctLat: 24.71,
    correctLng: 46.68,
    country: "Saudi Arabia",
    funFact: "Arabic is written from right to left and has influenced many languages — 'algebra', 'algorithm', and 'coffee' all come from Arabic.",
    difficulty: "medium",
  },
  {
    id: "turkish",
    name: "Turkish",
    nativeName: "Turkce",
    audioUrl: "/audio/turkish.mp3",
    correctLat: 41.01,
    correctLng: 28.98,
    country: "Turkey",
    funFact: "Turkish switched from Arabic script to Latin script overnight in 1928 as part of Ataturk's modernization reforms.",
    difficulty: "medium",
  },
  {
    id: "thai",
    name: "Thai",
    nativeName: "Phasa Thai",
    audioUrl: "/audio/thai.mp3",
    correctLat: 13.76,
    correctLng: 100.5,
    country: "Thailand",
    funFact: "Thai has 5 tones and its script has 44 consonants — one of the largest alphabets in the world.",
    difficulty: "hard",
  },
  {
    id: "vietnamese",
    name: "Vietnamese",
    nativeName: "Tieng Viet",
    audioUrl: "/audio/vietnamese.mp3",
    correctLat: 21.03,
    correctLng: 105.85,
    country: "Vietnam",
    funFact: "Vietnamese has 6 tones and uses Latin script with special diacritics, thanks to a 17th-century Portuguese missionary.",
    difficulty: "hard",
  },
  {
    id: "swahili",
    name: "Swahili",
    nativeName: "Kiswahili",
    audioUrl: "/audio/swahili.mp3",
    correctLat: -6.79,
    correctLng: 39.28,
    country: "Tanzania",
    funFact: "Swahili is a Bantu language heavily influenced by Arabic — it's the lingua franca of East Africa, spoken by over 100 million people.",
    difficulty: "hard",
  },
  {
    id: "dutch",
    name: "Dutch",
    nativeName: "Nederlands",
    audioUrl: "/audio/dutch.mp3",
    correctLat: 52.37,
    correctLng: 4.9,
    country: "Netherlands",
    funFact: "Dutch gave English words like 'cookie' (koekje), 'boss' (baas), and 'Santa Claus' (Sinterklaas).",
    difficulty: "medium",
  },
  {
    id: "polish",
    name: "Polish",
    nativeName: "Polski",
    audioUrl: "/audio/polish.mp3",
    correctLat: 52.23,
    correctLng: 21.01,
    country: "Poland",
    funFact: "Polish has 7 grammatical cases and the word 'szcz' (as in Szczecin) is a perfectly normal consonant cluster.",
    difficulty: "hard",
  },
  {
    id: "greek",
    name: "Greek",
    nativeName: "Ellinika",
    audioUrl: "/audio/greek.mp3",
    correctLat: 37.98,
    correctLng: 23.73,
    country: "Greece",
    funFact: "Greek has been continuously spoken for over 3,400 years, making it one of the oldest documented living languages.",
    difficulty: "medium",
  },
  {
    id: "hebrew",
    name: "Hebrew",
    nativeName: "Ivrit",
    audioUrl: "/audio/hebrew.mp3",
    correctLat: 32.07,
    correctLng: 34.78,
    country: "Israel",
    funFact: "Hebrew was a dead language for nearly 2,000 years before being revived as a spoken language in the late 19th century.",
    difficulty: "hard",
  },
  {
    id: "tamil",
    name: "Tamil",
    nativeName: "Tamil",
    audioUrl: "/audio/tamil.mp3",
    correctLat: 13.08,
    correctLng: 80.27,
    country: "India",
    funFact: "Tamil is over 2,000 years old and is one of the longest-surviving classical languages in the world.",
    difficulty: "hard",
  },
  {
    id: "yoruba",
    name: "Yoruba",
    nativeName: "Yoruba",
    audioUrl: "/audio/yoruba.mp3",
    correctLat: 6.52,
    correctLng: 3.38,
    country: "Nigeria",
    funFact: "Yoruba is a tonal language with 3 tones and is spoken by over 50 million people across West Africa and the diaspora.",
    difficulty: "hard",
  },
  {
    id: "indonesian",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    audioUrl: "/audio/indonesian.mp3",
    correctLat: -6.21,
    correctLng: 106.85,
    country: "Indonesia",
    funFact: "Indonesian has no verb conjugations, no grammatical gender, and no tones — making it one of the easiest Asian languages to learn.",
    difficulty: "medium",
  },
  {
    id: "swedish",
    name: "Swedish",
    nativeName: "Svenska",
    audioUrl: "/audio/swedish.mp3",
    correctLat: 59.33,
    correctLng: 18.07,
    country: "Sweden",
    funFact: "Swedish has a unique word 'lagom' meaning 'just the right amount' — a concept central to Swedish culture.",
    difficulty: "medium",
  },
  {
    id: "amharic",
    name: "Amharic",
    nativeName: "Amarinja",
    audioUrl: "/audio/amharic.mp3",
    correctLat: 9.02,
    correctLng: 38.75,
    country: "Ethiopia",
    funFact: "Amharic uses the Ge'ez script with 231 characters — each consonant has 7 forms depending on the vowel sound.",
    difficulty: "hard",
  },

  // ==================== EUROPE ====================

  {
    id: "romanian",
    name: "Romanian",
    nativeName: "Romana",
    audioUrl: "/audio/romanian.mp3",
    correctLat: 44.43,
    correctLng: 26.1,
    country: "Romania",
    funFact: "Romanian is the closest living language to Latin, retaining much of Latin's original grammatical structure including its case system.",
    difficulty: "medium",
  },
  {
    id: "danish",
    name: "Danish",
    nativeName: "Dansk",
    audioUrl: "/audio/danish.mp3",
    correctLat: 55.68,
    correctLng: 12.57,
    country: "Denmark",
    funFact: "Danish, Norwegian, and Swedish are mutually intelligible to a large degree, though Danes are famously hardest for the others to understand due to their pronunciation.",
    difficulty: "medium",
  },
  {
    id: "norwegian",
    name: "Norwegian",
    nativeName: "Norsk",
    audioUrl: "/audio/norwegian.mp3",
    correctLat: 59.91,
    correctLng: 10.75,
    country: "Norway",
    funFact: "Norway has two official written forms of Norwegian: Bokmal (based on Danish) and Nynorsk (based on rural dialects), and students must learn both.",
    difficulty: "medium",
  },
  {
    id: "finnish",
    name: "Finnish",
    nativeName: "Suomi",
    audioUrl: "/audio/finnish.mp3",
    correctLat: 60.17,
    correctLng: 24.94,
    country: "Finland",
    funFact: "Finnish is not an Indo-European language — it belongs to the Uralic family and is more closely related to Estonian and distantly to Hungarian.",
    difficulty: "hard",
  },
  {
    id: "czech",
    name: "Czech",
    nativeName: "Cestina",
    audioUrl: "/audio/czech.mp3",
    correctLat: 50.08,
    correctLng: 14.44,
    country: "Czech Republic",
    funFact: "Czech is famous for its consonant clusters — the tongue twister 'Strcprst skrz krk' (stick a finger through your throat) contains no vowels at all.",
    difficulty: "hard",
  },
  {
    id: "hungarian",
    name: "Hungarian",
    nativeName: "Magyar",
    audioUrl: "/audio/hungarian.mp3",
    correctLat: 47.5,
    correctLng: 19.04,
    country: "Hungary",
    funFact: "Hungarian belongs to the Uralic language family, making it completely unrelated to any of its neighboring Indo-European languages. It has 18 grammatical cases.",
    difficulty: "hard",
  },
  {
    id: "catalan",
    name: "Catalan",
    nativeName: "Catala",
    audioUrl: "/audio/catalan.mp3",
    correctLat: 41.39,
    correctLng: 2.17,
    country: "Spain",
    funFact: "Catalan is not a dialect of Spanish — it evolved independently from Vulgar Latin and is actually more closely related to Occitan, spoken in southern France.",
    difficulty: "medium",
  },
  {
    id: "galician",
    name: "Galician",
    nativeName: "Galego",
    audioUrl: "/audio/galician.mp3",
    correctLat: 42.88,
    correctLng: -8.54,
    country: "Spain",
    funFact: "Galician and Portuguese were once the same language called Galician-Portuguese, and they remain mutually intelligible to a significant extent today.",
    difficulty: "hard",
  },
  {
    id: "slovak",
    name: "Slovak",
    nativeName: "Slovencina",
    audioUrl: "/audio/slovak.mp3",
    correctLat: 48.15,
    correctLng: 17.11,
    country: "Slovakia",
    funFact: "Slovak and Czech are so closely related that speakers of each language can generally understand the other without any formal study, though younger generations find it harder.",
    difficulty: "hard",
  },
  {
    id: "bulgarian",
    name: "Bulgarian",
    nativeName: "Balgarski",
    audioUrl: "/audio/bulgarian.mp3",
    correctLat: 42.7,
    correctLng: 23.32,
    country: "Bulgaria",
    funFact: "Bulgarian was the first language to be written in the Cyrillic script, which was developed by disciples of Saints Cyril and Methodius in the 9th century.",
    difficulty: "hard",
  },
  {
    id: "serbian",
    name: "Serbian",
    nativeName: "Srpski",
    audioUrl: "/audio/serbian.mp3",
    correctLat: 44.79,
    correctLng: 20.47,
    country: "Serbia",
    funFact: "Serbian is one of the few languages in the world that officially uses two alphabets — both Cyrillic and Latin — and speakers switch between them freely.",
    difficulty: "hard",
  },
  {
    id: "croatian",
    name: "Croatian",
    nativeName: "Hrvatski",
    audioUrl: "/audio/croatian.mp3",
    correctLat: 45.81,
    correctLng: 15.98,
    country: "Croatia",
    funFact: "Croatian, Serbian, and Bosnian are linguistically almost identical and were once called Serbo-Croatian, but are now considered separate languages for political and cultural reasons.",
    difficulty: "medium",
  },
  {
    id: "bosnian",
    name: "Bosnian",
    nativeName: "Bosanski",
    audioUrl: "/audio/bosnian.mp3",
    correctLat: 43.86,
    correctLng: 18.41,
    country: "Bosnia and Herzegovina",
    funFact: "Bosnian is a pluricentric language that shares nearly all of its grammar and vocabulary with Croatian and Serbian, but incorporates more Turkish and Arabic loanwords due to Ottoman influence.",
    difficulty: "hard",
  },
  {
    id: "slovenian",
    name: "Slovenian",
    nativeName: "Slovenscina",
    audioUrl: "/audio/slovenian.mp3",
    correctLat: 46.06,
    correctLng: 14.51,
    country: "Slovenia",
    funFact: "Slovenian is one of the few languages that still uses the dual grammatical number, distinguishing between one, two, and more than two of something.",
    difficulty: "hard",
  },
  {
    id: "lithuanian",
    name: "Lithuanian",
    nativeName: "Lietuviu kalba",
    audioUrl: "/audio/lithuanian.mp3",
    correctLat: 54.69,
    correctLng: 25.28,
    country: "Lithuania",
    funFact: "Lithuanian is considered the most conservative living Indo-European language, retaining many archaic features of Proto-Indo-European that other languages lost thousands of years ago.",
    difficulty: "hard",
  },
  {
    id: "latvian",
    name: "Latvian",
    nativeName: "Latviesu valoda",
    audioUrl: "/audio/latvian.mp3",
    correctLat: 56.95,
    correctLng: 24.11,
    country: "Latvia",
    funFact: "Latvian and Lithuanian are the only two surviving Baltic languages, a branch of Indo-European that was once spoken across a much wider area of northeastern Europe.",
    difficulty: "hard",
  },
  {
    id: "estonian",
    name: "Estonian",
    nativeName: "Eesti keel",
    audioUrl: "/audio/estonian.mp3",
    correctLat: 59.44,
    correctLng: 24.75,
    country: "Estonia",
    funFact: "Estonian is closely related to Finnish rather than to its Baltic neighbors. It has 14 grammatical cases and no grammatical gender or future tense.",
    difficulty: "hard",
  },
  {
    id: "albanian",
    name: "Albanian",
    nativeName: "Shqip",
    audioUrl: "/audio/albanian.mp3",
    correctLat: 41.33,
    correctLng: 19.82,
    country: "Albania",
    funFact: "Albanian forms its own independent branch of the Indo-European language family, with no close living relatives — its origins remain one of linguistics' great mysteries.",
    difficulty: "hard",
  },
  {
    id: "macedonian",
    name: "Macedonian",
    nativeName: "Makedonski",
    audioUrl: "/audio/macedonian.mp3",
    correctLat: 42.0,
    correctLng: 21.43,
    country: "North Macedonia",
    funFact: "Macedonian is the most closely related language to Bulgarian, and like Bulgarian, it is one of the few Slavic languages to have lost its grammatical case system entirely.",
    difficulty: "hard",
  },
  {
    id: "ukrainian",
    name: "Ukrainian",
    nativeName: "Ukrainska",
    audioUrl: "/audio/ukrainian.mp3",
    correctLat: 50.45,
    correctLng: 30.52,
    country: "Ukraine",
    funFact: "Ukrainian is a distinct East Slavic language with its own unique vocabulary and melodic intonation. It is actually more closely related to Polish and Slovak than to Russian.",
    difficulty: "hard",
  },
  {
    id: "belarusian",
    name: "Belarusian",
    nativeName: "Belaruskaya",
    audioUrl: "/audio/belarusian.mp3",
    correctLat: 53.9,
    correctLng: 27.57,
    country: "Belarus",
    funFact: "Belarusian has historically been written in both Cyrillic and a Latin-based script called Lacinka, and it features a highly phonetic spelling system where words are written exactly as pronounced.",
    difficulty: "hard",
  },
  {
    id: "icelandic",
    name: "Icelandic",
    nativeName: "Islenska",
    audioUrl: "/audio/icelandic.mp3",
    correctLat: 64.15,
    correctLng: -21.94,
    country: "Iceland",
    funFact: "Icelandic has changed so little over the centuries that modern Icelanders can still read the medieval Norse sagas written 800 years ago with relative ease.",
    difficulty: "hard",
  },
  {
    id: "maltese",
    name: "Maltese",
    nativeName: "Malti",
    audioUrl: "/audio/maltese.mp3",
    correctLat: 35.9,
    correctLng: 14.51,
    country: "Malta",
    funFact: "Maltese is the only Semitic language written in the Latin alphabet and is an official language of the European Union. It descended from Arabic but absorbed heavy Italian and English influence.",
    difficulty: "hard",
  },
  {
    id: "luxembourgish",
    name: "Luxembourgish",
    nativeName: "Letzebuergesch",
    audioUrl: "/audio/luxembourgish.mp3",
    correctLat: 49.61,
    correctLng: 6.13,
    country: "Luxembourg",
    funFact: "Luxembourgish is a West Germanic language closely related to German dialects, but it only became Luxembourg's official national language in 1984 despite being spoken there for centuries.",
    difficulty: "hard",
  },
  {
    id: "welsh",
    name: "Welsh",
    nativeName: "Cymraeg",
    audioUrl: "/audio/welsh.mp3",
    correctLat: 51.48,
    correctLng: -3.18,
    country: "United Kingdom",
    funFact: "Welsh is a Celtic language that has experienced a remarkable revival — after decades of decline, the number of Welsh speakers has been growing, and it is now a required subject in Welsh schools.",
    difficulty: "hard",
  },
  {
    id: "irish",
    name: "Irish",
    nativeName: "Gaeilge",
    audioUrl: "/audio/irish.mp3",
    correctLat: 53.35,
    correctLng: -6.26,
    country: "Ireland",
    funFact: "Irish has the oldest vernacular literature in Western Europe, with written records dating back to the 6th century. It places the verb before the subject in sentence structure.",
    difficulty: "hard",
  },
  {
    id: "scottishGaelic",
    name: "Scottish Gaelic",
    nativeName: "Gaidhlig",
    audioUrl: "/audio/scottishGaelic.mp3",
    correctLat: 55.95,
    correctLng: -3.19,
    country: "United Kingdom",
    funFact: "Scottish Gaelic is a Celtic language brought to Scotland from Ireland around the 4th century. Despite having fewer than 60,000 speakers, it has seen a cultural renaissance through Gaelic-medium education.",
    difficulty: "hard",
  },
  {
    id: "basque",
    name: "Basque",
    nativeName: "Euskara",
    audioUrl: "/audio/basque.mp3",
    correctLat: 43.26,
    correctLng: -2.93,
    country: "Spain",
    funFact: "Basque is a language isolate with no known living relatives — it predates the arrival of Indo-European languages in Europe and may be the oldest language still spoken on the continent.",
    difficulty: "hard",
  },
  {
    id: "corsican",
    name: "Corsican",
    nativeName: "Corsu",
    audioUrl: "/audio/corsican.mp3",
    correctLat: 41.93,
    correctLng: 8.74,
    country: "France",
    funFact: "Corsican is closely related to Tuscan Italian and was actually classified as an Italian dialect until the 20th century. Napoleon Bonaparte grew up speaking Corsican before learning French.",
    difficulty: "hard",
  },
  {
    id: "yiddish",
    name: "Yiddish",
    nativeName: "Yidish",
    audioUrl: "/audio/yiddish.mp3",
    correctLat: 50.06,
    correctLng: 19.94,
    country: "Poland",
    funFact: "Yiddish is a Germanic language written in the Hebrew alphabet. It gave English many common words including 'bagel', 'chutzpah', 'glitch', 'klutz', and 'schmuck'.",
    difficulty: "hard",
  },

  // ==================== MIDDLE EAST / CENTRAL ASIA ====================

  {
    id: "georgian",
    name: "Georgian",
    nativeName: "Kartuli",
    audioUrl: "/audio/georgian.mp3",
    correctLat: 41.72,
    correctLng: 44.79,
    country: "Georgia",
    funFact: "Georgian has its own unique alphabet that is one of only 14 scripts in use today. It allows consonant clusters of up to eight consonants, as in the word 'gvprtskvni' (you peel us).",
    difficulty: "hard",
  },
  {
    id: "armenian",
    name: "Armenian",
    nativeName: "Hayeren",
    audioUrl: "/audio/armenian.mp3",
    correctLat: 40.18,
    correctLng: 44.51,
    country: "Armenia",
    funFact: "The Armenian alphabet was created by the monk Mesrop Mashtots in 405 AD specifically for the Armenian language. Armenian forms its own independent branch of the Indo-European family.",
    difficulty: "hard",
  },
  {
    id: "azerbaijani",
    name: "Azerbaijani",
    nativeName: "Azerbaycanca",
    audioUrl: "/audio/azerbaijani.mp3",
    correctLat: 40.41,
    correctLng: 49.87,
    country: "Azerbaijan",
    funFact: "Azerbaijani is a Turkic language so close to Turkish that speakers of both languages can largely understand each other. It has been written in Arabic, Latin, and Cyrillic scripts at various points in history.",
    difficulty: "medium",
  },
  {
    id: "kazakh",
    name: "Kazakh",
    nativeName: "Qazaq tili",
    audioUrl: "/audio/kazakh.mp3",
    correctLat: 51.17,
    correctLng: 71.43,
    country: "Kazakhstan",
    funFact: "Kazakhstan is currently transitioning the Kazakh language from Cyrillic to Latin script, a process expected to be completed by 2031 — the third script change in 100 years.",
    difficulty: "hard",
  },
  {
    id: "uzbek",
    name: "Uzbek",
    nativeName: "O'zbek tili",
    audioUrl: "/audio/uzbek.mp3",
    correctLat: 41.3,
    correctLng: 69.28,
    country: "Uzbekistan",
    funFact: "Uzbek is a Turkic language that has been written in Arabic, Latin, and Cyrillic scripts. It is the most widely spoken Turkic language in Central Asia with over 30 million native speakers.",
    difficulty: "hard",
  },
  {
    id: "kyrgyz",
    name: "Kyrgyz",
    nativeName: "Kyrgyz tili",
    audioUrl: "/audio/kyrgyz.mp3",
    correctLat: 42.87,
    correctLng: 74.59,
    country: "Kyrgyzstan",
    funFact: "The Epic of Manas, an oral poem traditionally recited in Kyrgyz, is one of the longest epic poems in the world — twenty times longer than the Iliad and the Odyssey combined.",
    difficulty: "hard",
  },
  {
    id: "tajik",
    name: "Tajik",
    nativeName: "Tojiki",
    audioUrl: "/audio/tajik.mp3",
    correctLat: 38.56,
    correctLng: 68.77,
    country: "Tajikistan",
    funFact: "Tajik is a variety of Persian written in the Cyrillic alphabet. Speakers of Tajik, Iranian Persian, and Afghan Dari can largely understand each other despite using different scripts.",
    difficulty: "hard",
  },
  {
    id: "persian",
    name: "Persian",
    nativeName: "Farsi",
    audioUrl: "/audio/persian.mp3",
    correctLat: 35.69,
    correctLng: 51.39,
    country: "Iran",
    funFact: "Persian has been a major literary language for over a millennium. It has remarkably simple grammar with no grammatical gender, no noun cases, and no articles.",
    difficulty: "medium",
  },
  {
    id: "pashto",
    name: "Pashto",
    nativeName: "Pashto",
    audioUrl: "/audio/pashto.mp3",
    correctLat: 34.53,
    correctLng: 69.17,
    country: "Afghanistan",
    funFact: "Pashto is an ancient Iranian language with a rich oral poetry tradition called Landai — two-line folk poems, often composed by women, that distill complex emotions into just 22 syllables.",
    difficulty: "hard",
  },
  {
    id: "kurdish",
    name: "Kurdish",
    nativeName: "Kurdi",
    audioUrl: "/audio/kurdish.mp3",
    correctLat: 36.19,
    correctLng: 44.01,
    country: "Iraq",
    funFact: "Kurdish is an Iranian language spoken by over 30 million people across four countries, yet it has no single nation-state. It is written in Latin, Arabic, and Cyrillic scripts depending on the region.",
    difficulty: "hard",
  },
  {
    id: "turkmen",
    name: "Turkmen",
    nativeName: "Turkmen dili",
    audioUrl: "/audio/turkmen.mp3",
    correctLat: 37.95,
    correctLng: 58.38,
    country: "Turkmenistan",
    funFact: "Turkmen is a Turkic language with strong vowel harmony. It switched from Arabic to Latin script in 1929, then to Cyrillic in 1940, and back to a modified Latin script in 1993.",
    difficulty: "hard",
  },
  {
    id: "mongolian",
    name: "Mongolian",
    nativeName: "Mongol khel",
    audioUrl: "/audio/mongolian.mp3",
    correctLat: 47.92,
    correctLng: 106.91,
    country: "Mongolia",
    funFact: "Traditional Mongolian script is written vertically from top to bottom, making it one of the only vertical scripts still in use. Mongolia has been reintroducing it alongside Cyrillic.",
    difficulty: "hard",
  },

  // ==================== SOUTH ASIA ====================

  {
    id: "urdu",
    name: "Urdu",
    nativeName: "Urdu",
    audioUrl: "/audio/urdu.mp3",
    correctLat: 33.69,
    correctLng: 73.04,
    country: "Pakistan",
    funFact: "Urdu and Hindi are nearly identical in everyday speech but use completely different scripts — Urdu uses a modified Arabic script called Nastaliq, while Hindi uses Devanagari.",
    difficulty: "medium",
  },
  {
    id: "bengali",
    name: "Bengali",
    nativeName: "Bangla",
    audioUrl: "/audio/bengali.mp3",
    correctLat: 23.81,
    correctLng: 90.41,
    country: "Bangladesh",
    funFact: "Bengali is the 7th most spoken language in the world. Bangladesh's Language Movement of 1952, which fought for Bengali's recognition, is now commemorated as International Mother Language Day by UNESCO.",
    difficulty: "medium",
  },
  {
    id: "punjabi",
    name: "Punjabi",
    nativeName: "Panjabi",
    audioUrl: "/audio/punjabi.mp3",
    correctLat: 31.55,
    correctLng: 74.35,
    country: "Pakistan",
    funFact: "Punjabi is the most widely spoken language in Pakistan and the 10th most spoken language worldwide. It is written in two scripts: Shahmukhi (Arabic-based) in Pakistan and Gurmukhi in India.",
    difficulty: "medium",
  },
  {
    id: "gujarati",
    name: "Gujarati",
    nativeName: "Gujarati",
    audioUrl: "/audio/gujarati.mp3",
    correctLat: 23.02,
    correctLng: 72.57,
    country: "India",
    funFact: "Gujarati was Mahatma Gandhi's mother tongue. It is one of the oldest Indo-Aryan languages with a rich literary tradition dating back to the 12th century.",
    difficulty: "hard",
  },
  {
    id: "marathi",
    name: "Marathi",
    nativeName: "Marathi",
    audioUrl: "/audio/marathi.mp3",
    correctLat: 19.08,
    correctLng: 72.88,
    country: "India",
    funFact: "Marathi is the oldest of the regional literatures in Indo-Aryan languages, with written records dating back to the 11th century. It has over 83 million native speakers.",
    difficulty: "hard",
  },
  {
    id: "telugu",
    name: "Telugu",
    nativeName: "Telugu",
    audioUrl: "/audio/telugu.mp3",
    correctLat: 17.39,
    correctLng: 78.49,
    country: "India",
    funFact: "Telugu is known as the 'Italian of the East' because, like Italian, every native Telugu word ends in a vowel. It has over 82 million native speakers.",
    difficulty: "hard",
  },
  {
    id: "kannada",
    name: "Kannada",
    nativeName: "Kannada",
    audioUrl: "/audio/kannada.mp3",
    correctLat: 12.97,
    correctLng: 77.59,
    country: "India",
    funFact: "Kannada has a continuous literary history spanning over 1,500 years. The Kannada script evolved from the Kadamba and Chalukya scripts and is one of the oldest Dravidian writing systems.",
    difficulty: "hard",
  },
  {
    id: "malayalam",
    name: "Malayalam",
    nativeName: "Malayalam",
    audioUrl: "/audio/malayalam.mp3",
    correctLat: 8.52,
    correctLng: 76.94,
    country: "India",
    funFact: "Malayalam is a palindrome in English. It is the youngest of the major Dravidian languages, having diverged from Tamil around the 9th century, and Kerala (where it is spoken) has India's highest literacy rate.",
    difficulty: "hard",
  },
  {
    id: "sinhala",
    name: "Sinhala",
    nativeName: "Sinhala",
    audioUrl: "/audio/sinhala.mp3",
    correctLat: 6.93,
    correctLng: 79.85,
    country: "Sri Lanka",
    funFact: "Sinhala has one of the most rounded and curvy scripts in the world, developed partly because palm leaves (the traditional writing material) would tear if straight lines were used.",
    difficulty: "hard",
  },
  {
    id: "nepali",
    name: "Nepali",
    nativeName: "Nepali",
    audioUrl: "/audio/nepali.mp3",
    correctLat: 27.72,
    correctLng: 85.32,
    country: "Nepal",
    funFact: "Nepali uses the Devanagari script like Hindi but has distinct vocabulary and pronunciation. It is also an official language of the Indian state of Sikkim and is spoken widely in Bhutan.",
    difficulty: "hard",
  },

  // ==================== SOUTHEAST ASIA ====================

  {
    id: "burmese",
    name: "Burmese",
    nativeName: "Myanma bhasa",
    audioUrl: "/audio/burmese.mp3",
    correctLat: 19.76,
    correctLng: 96.07,
    country: "Myanmar",
    funFact: "Burmese script is famously circular — its round shapes evolved because the traditional writing material, palm leaves, would split along straight lines.",
    difficulty: "hard",
  },
  {
    id: "lao",
    name: "Lao",
    nativeName: "Phasa Lao",
    audioUrl: "/audio/lao.mp3",
    correctLat: 17.97,
    correctLng: 102.63,
    country: "Laos",
    funFact: "Lao and Thai are closely related and partially mutually intelligible. Lao has six tones and its script, while similar to Thai, has fewer characters because French colonial influence simplified the spelling system.",
    difficulty: "hard",
  },
  {
    id: "khmer",
    name: "Khmer",
    nativeName: "Phasa Khmer",
    audioUrl: "/audio/khmer.mp3",
    correctLat: 11.56,
    correctLng: 104.92,
    country: "Cambodia",
    funFact: "The Khmer alphabet holds the Guinness World Record for the largest alphabet in the world with 74 characters. Unlike Thai and Vietnamese, Khmer is not a tonal language.",
    difficulty: "hard",
  },
  {
    id: "malay",
    name: "Malay",
    nativeName: "Bahasa Melayu",
    audioUrl: "/audio/malay.mp3",
    correctLat: 3.14,
    correctLng: 101.69,
    country: "Malaysia",
    funFact: "Malay and Indonesian are so similar that speakers can understand each other with ease. Malay has been a major trade language across Southeast Asia for over a thousand years.",
    difficulty: "medium",
  },
  {
    id: "tagalog",
    name: "Tagalog",
    nativeName: "Tagalog",
    audioUrl: "/audio/tagalog.mp3",
    correctLat: 14.6,
    correctLng: 120.98,
    country: "Philippines",
    funFact: "Tagalog (the basis for Filipino) has absorbed thousands of Spanish loanwords from over 300 years of colonization — words like 'kutsara' (cuchara/spoon) and 'silya' (silla/chair) are everyday vocabulary.",
    difficulty: "medium",
  },
  {
    id: "cebuano",
    name: "Cebuano",
    nativeName: "Sinugbuanon",
    audioUrl: "/audio/cebuano.mp3",
    correctLat: 10.31,
    correctLng: 123.89,
    country: "Philippines",
    funFact: "Cebuano is actually the most spoken native language in the Philippines by number of native speakers, surpassing Tagalog. It has over 20 million native speakers across the Visayas and Mindanao regions.",
    difficulty: "hard",
  },
  {
    id: "javanese",
    name: "Javanese",
    nativeName: "Basa Jawa",
    audioUrl: "/audio/javanese.mp3",
    correctLat: -7.8,
    correctLng: 110.36,
    country: "Indonesia",
    funFact: "Javanese has elaborate speech levels (ngoko, madya, krama) that change vocabulary and grammar depending on the social relationship between speakers — using the wrong level is a serious faux pas.",
    difficulty: "hard",
  },
  {
    id: "hmong",
    name: "Hmong",
    nativeName: "Lus Hmoob",
    audioUrl: "/audio/hmong.mp3",
    correctLat: 19.84,
    correctLng: 102.14,
    country: "Laos",
    funFact: "Hmong is a tonal language with up to eight tones in some dialects. It had no widely used writing system until the 1950s, when missionaries created the Romanized Popular Alphabet still used today.",
    difficulty: "hard",
  },

  // ==================== AFRICA ====================

  {
    id: "afrikaans",
    name: "Afrikaans",
    nativeName: "Afrikaans",
    audioUrl: "/audio/afrikaans.mp3",
    correctLat: -33.93,
    correctLng: 18.42,
    country: "South Africa",
    funFact: "Afrikaans evolved from 17th-century Dutch spoken by settlers in South Africa. It is the youngest Germanic language, having become standardized only in the early 20th century.",
    difficulty: "medium",
  },
  {
    id: "zulu",
    name: "Zulu",
    nativeName: "isiZulu",
    audioUrl: "/audio/zulu.mp3",
    correctLat: -29.86,
    correctLng: 31.02,
    country: "South Africa",
    funFact: "Zulu has three types of click consonants borrowed from the Khoisan languages. It is the most widely spoken home language in South Africa with over 12 million native speakers.",
    difficulty: "hard",
  },
  {
    id: "xhosa",
    name: "Xhosa",
    nativeName: "isiXhosa",
    audioUrl: "/audio/xhosa.mp3",
    correctLat: -33.02,
    correctLng: 27.91,
    country: "South Africa",
    funFact: "Xhosa is famous for its 18 click consonants, more than any other Bantu language. The 'X' in Xhosa itself represents a lateral click sound made by pulling the tongue from the side of the mouth.",
    difficulty: "hard",
  },
  {
    id: "sotho",
    name: "Sotho",
    nativeName: "Sesotho",
    audioUrl: "/audio/sotho.mp3",
    correctLat: -29.31,
    correctLng: 27.48,
    country: "Lesotho",
    funFact: "Sotho is one of the few African languages that is the dominant language of an entire country (Lesotho). Its noun class system groups nouns into categories that determine agreement patterns across entire sentences.",
    difficulty: "hard",
  },
  {
    id: "igbo",
    name: "Igbo",
    nativeName: "Igbo",
    audioUrl: "/audio/igbo.mp3",
    correctLat: 6.45,
    correctLng: 3.39,
    country: "Nigeria",
    funFact: "Igbo has a unique tonal system and was historically written in Nsibidi, an ancient ideographic script developed independently in West Africa that dates back to at least the 4th century.",
    difficulty: "hard",
  },
  {
    id: "hausa",
    name: "Hausa",
    nativeName: "Hausa",
    audioUrl: "/audio/hausa.mp3",
    correctLat: 12.0,
    correctLng: 8.52,
    country: "Nigeria",
    funFact: "Hausa is the most widely spoken language in West Africa with over 70 million speakers. It is a major trade language and has a rich literary tradition in both Arabic (Ajami) and Latin scripts.",
    difficulty: "medium",
  },
  {
    id: "somali",
    name: "Somali",
    nativeName: "Af Soomaali",
    audioUrl: "/audio/somali.mp3",
    correctLat: 2.05,
    correctLng: 45.32,
    country: "Somalia",
    funFact: "Somali did not have an official written form until 1972, making it one of the last major languages to adopt a standardized script. Before that, it had one of the richest oral poetry traditions in the world.",
    difficulty: "hard",
  },
  {
    id: "oromo",
    name: "Oromo",
    nativeName: "Afaan Oromoo",
    audioUrl: "/audio/oromo.mp3",
    correctLat: 9.02,
    correctLng: 38.75,
    country: "Ethiopia",
    funFact: "Oromo is the most widely spoken language in Ethiopia and one of the most spoken languages in all of Africa. It was banned from written use for decades until 1991, when it adopted the Latin-based Qubee alphabet.",
    difficulty: "hard",
  },
  {
    id: "tigrinya",
    name: "Tigrinya",
    nativeName: "Tigrinya",
    audioUrl: "/audio/tigrinya.mp3",
    correctLat: 15.34,
    correctLng: 38.93,
    country: "Eritrea",
    funFact: "Tigrinya uses the ancient Ge'ez script, one of the oldest alphabets in continuous use. Each of its 32 base consonants has seven different forms for different vowel sounds, creating over 200 distinct characters.",
    difficulty: "hard",
  },
  {
    id: "malagasy",
    name: "Malagasy",
    nativeName: "Malagasy",
    audioUrl: "/audio/malagasy.mp3",
    correctLat: -18.88,
    correctLng: 47.51,
    country: "Madagascar",
    funFact: "Despite Madagascar being off the coast of Africa, Malagasy is an Austronesian language most closely related to languages spoken in Borneo, Indonesia — evidence of an incredible ancient ocean migration.",
    difficulty: "hard",
  },
  {
    id: "kinyarwanda",
    name: "Kinyarwanda",
    nativeName: "Ikinyarwanda",
    audioUrl: "/audio/kinyarwanda.mp3",
    correctLat: -1.94,
    correctLng: 30.06,
    country: "Rwanda",
    funFact: "Kinyarwanda is one of the few African languages spoken by an entire nation as a mother tongue — virtually all Rwandans speak it, making Rwanda one of the most linguistically homogeneous countries in Africa.",
    difficulty: "hard",
  },
  {
    id: "lingala",
    name: "Lingala",
    nativeName: "Lingala",
    audioUrl: "/audio/lingala.mp3",
    correctLat: -4.44,
    correctLng: 15.27,
    country: "DR Congo",
    funFact: "Lingala is the language of Congolese popular music (soukous and rumba), which has made it a lingua franca across Central Africa. It spread largely through music, trade, and the military.",
    difficulty: "hard",
  },
  {
    id: "wolof",
    name: "Wolof",
    nativeName: "Wolof",
    audioUrl: "/audio/wolof.mp3",
    correctLat: 14.72,
    correctLng: -17.47,
    country: "Senegal",
    funFact: "Wolof is so dominant in Senegal that it has become the country's true lingua franca, spoken by over 80% of the population even though it is the native language of only about 40%.",
    difficulty: "hard",
  },
  {
    id: "tswana",
    name: "Tswana",
    nativeName: "Setswana",
    audioUrl: "/audio/tswana.mp3",
    correctLat: -24.65,
    correctLng: 25.91,
    country: "Botswana",
    funFact: "Tswana is the national language of Botswana (whose name means 'land of the Tswana people') and is also one of the 11 official languages of South Africa. It has a rich tradition of praise poetry.",
    difficulty: "hard",
  },
  {
    id: "shona",
    name: "Shona",
    nativeName: "chiShona",
    audioUrl: "/audio/shona.mp3",
    correctLat: -17.83,
    correctLng: 31.05,
    country: "Zimbabwe",
    funFact: "Shona is spoken by about 80% of Zimbabwe's population. It is closely associated with the mbira (thumb piano), a musical instrument central to Shona spiritual and cultural ceremonies for centuries.",
    difficulty: "hard",
  },

  // ==================== AMERICAS / PACIFIC ====================

  {
    id: "haitianCreole",
    name: "Haitian Creole",
    nativeName: "Kreyol Ayisyen",
    audioUrl: "/audio/haitianCreole.mp3",
    correctLat: 18.54,
    correctLng: -72.34,
    country: "Haiti",
    funFact: "Haitian Creole is a French-based creole language that became Haiti's official language alongside French in 1987. While its vocabulary is mostly French-derived, its grammar is largely influenced by West African languages.",
    difficulty: "medium",
  },
  {
    id: "quechua",
    name: "Quechua",
    nativeName: "Runasimi",
    audioUrl: "/audio/quechua.mp3",
    correctLat: -13.53,
    correctLng: -71.97,
    country: "Peru",
    funFact: "Quechua was the language of the Inca Empire and is still spoken by over 8 million people across South America. The words 'condor', 'jerky', 'llama', and 'quinoa' all come from Quechua.",
    difficulty: "hard",
  },
  {
    id: "guarani",
    name: "Guarani",
    nativeName: "Avane'e",
    audioUrl: "/audio/guarani.mp3",
    correctLat: -25.26,
    correctLng: -57.58,
    country: "Paraguay",
    funFact: "Guarani is co-official with Spanish in Paraguay and is one of the few indigenous American languages spoken by a majority non-indigenous population — about 90% of Paraguayans speak it.",
    difficulty: "hard",
  },
  {
    id: "hawaiian",
    name: "Hawaiian",
    nativeName: "'Olelo Hawai'i",
    audioUrl: "/audio/hawaiian.mp3",
    correctLat: 21.31,
    correctLng: -157.86,
    country: "United States",
    funFact: "Hawaiian has one of the smallest phoneme inventories of any language, with only 13 letters (8 consonants and 5 vowels). It was nearly extinct by the 1980s but has been revived through immersion schools.",
    difficulty: "hard",
  },
  {
    id: "maori",
    name: "Maori",
    nativeName: "Te Reo Maori",
    audioUrl: "/audio/maori.mp3",
    correctLat: -41.29,
    correctLng: 174.78,
    country: "New Zealand",
    funFact: "Maori is a Polynesian language that has experienced a remarkable revival. New Zealand's iconic greeting 'kia ora' and the world-famous haka performed by the All Blacks are in Te Reo Maori.",
    difficulty: "hard",
  },
  {
    id: "samoan",
    name: "Samoan",
    nativeName: "Gagana Samoa",
    audioUrl: "/audio/samoan.mp3",
    correctLat: -13.83,
    correctLng: -171.76,
    country: "Samoa",
    funFact: "Samoan is one of the oldest and most widely spoken Polynesian languages. It has a formal register called 'gagana fa'aaloalo' used when addressing chiefs, which uses completely different vocabulary from everyday speech.",
    difficulty: "hard",
  },
  {
    id: "tongan",
    name: "Tongan",
    nativeName: "Lea Faka-Tonga",
    audioUrl: "/audio/tongan.mp3",
    correctLat: -21.21,
    correctLng: -175.2,
    country: "Tonga",
    funFact: "Tongan is a Polynesian language spoken in the Kingdom of Tonga, the only Pacific Island nation never colonized by a European power. Like other Polynesian languages, it has only 16 consonants and 5 vowels.",
    difficulty: "hard",
  },
  {
    id: "fijian",
    name: "Fijian",
    nativeName: "Vosa Vakaviti",
    audioUrl: "/audio/fijian.mp3",
    correctLat: -18.14,
    correctLng: 178.44,
    country: "Fiji",
    funFact: "Fijian spelling can surprise newcomers — the letter 'b' is pronounced 'mb', 'd' is pronounced 'nd', and 'c' is pronounced 'th'. So the city Nadi is actually pronounced 'Nandi'.",
    difficulty: "hard",
  },

  // ==================== CONSTRUCTED / OTHER ====================

  {
    id: "esperanto",
    name: "Esperanto",
    nativeName: "Esperanto",
    audioUrl: "/audio/esperanto.mp3",
    correctLat: 52.23,
    correctLng: 21.01,
    country: "Poland",
    funFact: "Esperanto was created in 1887 by L.L. Zamenhof in Warsaw as an easy-to-learn international auxiliary language. It is the most successful constructed language, with an estimated 2 million speakers worldwide.",
    difficulty: "hard",
  },
  {
    id: "scots",
    name: "Scots",
    nativeName: "Scots",
    audioUrl: "/audio/scots.mp3",
    correctLat: 55.95,
    correctLng: -3.19,
    country: "United Kingdom",
    funFact: "Scots is a Germanic language distinct from Scottish Gaelic — it descended from Old English alongside modern English but diverged in the Middle Ages. Robert Burns wrote many of his famous poems in Scots.",
    difficulty: "hard",
  },
];
